tag == EXIF_TAG_MAKE ||
		tag == EXIF_TAG_MODEL ||
		tag == EXIF_TAG_IMAGE_DESCRIPTION ||
		tag == EXIF_TAG_ARTIST ||
		tag == EXIF_TAG_SOFTWARE ||
		tag == EXIF_TAG_COPYRIGHT ||
		tag == EXIF_TAG_DATE_TIME ||
		tag == EXIF_TAG_DATE_TIME_ORIGINAL ||
		tag == EXIF_TAG_DATE_TIME_DIGITIZED ||
		tag == EXIF_TAG_SUB_SEC_TIME ||
		tag == EXIF_TAG_SUB_SEC_TIME_ORIGINAL ||
		tag == EXIF_TAG_SUB_SEC_TIME_DIGITIZED
#ifdef HAVE_EXIF_2_3_ASCII_TAGS
		|| tag == EXIF_TAG_CAMERA_OWNER_NAME
		|| tag == EXIF_TAG_BODY_SERIAL_NUMBER
		|| tag == EXIF_TAG_LENS_MAKE
		|| tag == EXIF_TAG_LENS_MODEL
		|| tag == EXIF_TAG_LENS_SERIAL_NUMBER